import { Manrope } from "next/font/google";
import "./globals.css";
import { Navigation } from "../ui/navigation/navigation";

const manrope = Manrope({
  subsets: ["latin", "cyrillic"],
});

export const metadata = {
  title: "Create My New Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="ru"
      className={manrope.className}
    >
      <body>
        <Navigation />

        <main className="p-4">
          {children}
        </main>
      </body>
    </html>
  );
}
